<?php 
include_once(__dir__.'/../../../components/carousel/home-carousel.php');
include_once(__dir__.'/../../../components/topics/topiclist.php');
include_once(__dir__.'/../../../components/banners/banner-top.php');
include_once(__dir__.'/../../../components/banners/banners.php');
include_once(__dir__.'/../../../components/videos/video-list.php');
include_once(__dir__.'/../../../components/recommendations/recommend.php');
include_once(__dir__.'/../../../components/destinations/feature_destination.php');
include_once(__dir__.'/../../../components/blogs/blog-list.php');
include_once(__dir__.'/../../../components/banners/banner-bo.php');
?>
